name: Run Unit Tests

on:
  push:
    paths:
      - 'pronotepy/**.py'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Install dev dependencies
        run: python -m pip install -r requirements.txt
      - name: Run mypy
        run: python -m mypy pronotepy --exclude pronotepy.test_pronotepy
